let admin ={
    email:`amin123@gmail.com`,
    password:`amin123`,
    permission:`admin`,
}

let user = [
    {
        name: `Nguyen Huu Hop`,
        age: 20,
        address: `Ha Noi`,
        phoneNumber: 033123456,
        email: `hop123@gmail.com`,
        password: `hop123`,
        permission:`user`,

    },{
        name: `Phung Duc Trung`,
        age: 20,
        address: `Ha Noi`,
        phoneNumber: 135791113,
        email: `trung123@gmail.com`,
        password: `trung123`,
        permission:`user`,
    },{
        name: `Do Minh Khue`,
        age: 20,
        address: `Ha Noi`,
        phoneNumber: 246810121,
        email: `khue123@gmail.com`,
        password: `khue123`,
        permission:`user`,
    }
]

let productsData = [
    {
        name:`L’Interdit`,
        brand:`Givenchy`,
        price:2600000,
        imageUrl:`./Media/image/perfume/LINTERDIT.png`,
        size:`80ml`,
        sex: `female`,
        scent:[
            'poppy',
            'musk',
            'vetiver grass',
        ],
    },
    {
        name:`La Nuit De L’homme EDT`,
        brand:`Yves Saint Laurent`,
        price:2950000,
        imageUrl: `./Media/image/perfume/La Nuit De L’homme EDT.png` ,
        size:`100ml`,
        sex:`male`,
        scent:[
            'lavender',
            'snowwood',
            'cardamom',
        ],
    },
    {
        name:`Bloom Acqua Di Fiori`,
        brand:`Gucci`,
        price:3000000,
        imageUrl:`./Media/image/perfume/Bloom-acqua-Di-Fiori-EDT.png`,
        size:`100ml`,
        sex: `female`,
        scent:[
            'yellow lemon',
            'freesia',
            'sandalwood',
        ],
    },
      {
        name:`Sauvage Parfum`,
        brand:`Dior`,
        price:3850000,
        imageUrl:`./Media/image/perfume/Sauvage Parfum.png`,
        size:`100ml`,
        sex:`male`,
        scent:[
            'vanilla',
            'frankincense',
            'sandalwood',

        ],
    }, {
        name:`Chanel Coco Noir`,
        brand:`Chanel`,
        price:4250000,
        imageUrl:`./Media/image/perfume/Chanel Coco Noir.png`,
        size:`100ml`,
        sex:`female`,
        scent:[
            'orange',
            'rose',
            'tonka beans',
        ],
    },
    {
        name:`Scandal`,
        brand:`jean Paul Gaultier`,
        price:2950000,
        imageUrl:`./Media/image/perfume/scandal.png`,
        size:`80ml`,
        sex: `female`,
        scent:[
            'red orange',
            'jasmine',
            'road wins',
        ],
    },
     {
        name:`Ombre Leather EDP`,
        brand:`Tom Ford`,
        price:4700000,
        imageUrl:`./Media/image/perfume/Ombre Leather EDP.png`,
        size:`100ml`,
        sex:`male`,
        scent:[
            'leather',
            'cardamom',
            'moss moss',
        ],
    }, 
    {
        name:`Eros EDT`,
        brand:`Versace`,
        price:2500000,
        imageUrl:`./Media/image/perfume/eros-edt.png`,
        size:`100ml`,
        sex: `male`,
        scent:[
            'mint',
            'tonka beans',
            'vanilla',
        ],
    },
    {
        name:`My Burberry Blush`,
        brand:`Burberry`,
        price:3750000,
        imageUrl:`./Media/image/perfume/My Burberry Blush.png`,
        size:`100ml`,
        sex: `female`,
        scent:[
            'yellow lemon',
            'rose',
            'purple flowers',
        ],
    },{
        name:`Twilly d’Hermès`,
        brand:`Hermès`,
        price:2950000,
        imageUrl:`./Media/image/perfume/Twilly d’Hermès.png`,
        size:`85ml`,
        sex: `female`,
        scent:[
            'ginger',
            'jasmine',
            'sandalwood',
        ],
    },
    {
        name:`L’homme Prada L’eau`,
        brand:`Prada`,
        price:3250000,
        imageUrl:`./Media/image/perfume/leau.png`,
        size:`100ml`,
        sex: `male`,
        scent:[
            'neroli',
            'amber',
            'snowwood',
        ],
    },
    {
        name:`Un Jardin Sur Le Nil`,
        brand:`Hermès`,
        price:2800000,
        imageUrl:`./Media/image/perfume/Un Jardin Sur Le Nil.png`,
        size:`100ml`,
        sex: `unisex`,
        scent:[
            'pomelo',
            'peony',
            'musk',
        ],
    },{
        name:`Gentleman`,
        brand:`Givenchy`,
        price:3000000,
        imageUrl:`./Media/image/perfume/Gentleman.png`,
        size:`100ml`,
        sex: `male`,
        scent:[
            'black pepper',
            'clove',
            'benzoin',
        ],
    },{
        name:`Boss The Scent Intense For Men`,
        brand:`Hugo Boss`,
        price:3150000,
        imageUrl:`./Media/image/perfume/boss.png`,
        size:`100ml`,
        sex: `male`,
        scent:[
            'cardamom',
            'lavender',
            'leather',
        ],
    },{
        name:`Ultra Male`,
        brand:`jean Paul Gaultier`,
        price:2950000,
        imageUrl:`./Media/image/perfume/ultra-male.png`,
        size:`125ml`,
        sex: `male`,
        scent:[
            'pear',
            'lavender',
            'amber',
        ],
    },{
        name:`Libre`,
        brand:`Yves Saint Laurent`,
        price:3400000,
        imageUrl:`./Media/image/perfume/Libre.png`,
        size:`90ml`,
        sex:`female`,
        scent:[
            'orange madarin',
            'lavender',
            'musk',
        ],
    },{
        name:`Dior Sauvage EDT`,
        brand:`Dior`,
        price:3150000,
        imageUrl:`./Media/image/perfume/Dior Sauvage EDT.png`,
        size:`100ml`,
        sex:`male`,
        scent:[
            'black pepper',
            'snowwood',
            'ambroxan',
        ],
    },{
        name:`Chanel Chance EDT`,
        brand:`Chanel`,
        price:3400000,
        imageUrl:`./Media/image/perfume/Chanel Chance EDT.png`,
        size:`100ml`,
        sex:`female`,
        scent:[
            'pineapple',
            'jasmine',
            'vanilla',
        ],
    },{
        name:`Noir de Noir`,
        brand:`Tom Ford`,
        price:8000000,
        imageUrl:`./Media/image/perfume/Noir de Noir.png`,
        size:`100ml`,
        sex: `unisex`,
        scent:[
            'saffron flowers',
            'rose',
            'oak tree',
        ],
    },{
        name:`Mr. Burberry EDP`,
        brand:`Burberry`,
        price:3000000,
        imageUrl:`./Media/image/perfume/Mr. Burberry EDP.png`,
        size:`100ml`,
        sex: `male`,
        scent:[
            'cinnamon',
            'snowwood',
            'amber',
        ],
    },
]
